[DEFAULT]
dataset = May282026_UGA_HRMAS_13C_Cells

[paths]
input_dir = /data/local/jy1008/MA-host-microbiome/dfba_JY/nmr_area_estimation/data/%(dataset)s/raw
output_dir = /data/local/jy1008/MA-host-microbiome/dfba_JY/nmr_area_estimation/data/%(dataset)s/processed_xlsx

# For use with s = Stack()
[experiment]
# 1H or 13C
spectra_type = 1H_standard
# fid used to perform the calibration
first_fid = 21


# 21: zgpr (1H_standard)
# 22: noesyprigld1d
# 23: zgpg30 (13C)
# 24: hsqcphpr
# 25: hsqcphpr (1H_mixture)

# def match_pulprog(isotope, pulprog, fid=None):
#     # original pulprog
#     if isotope == '1H':
#         return pulprog == 'noesypr1d'
#     elif isotope == '13C':
#         return pulprog == 'zgpg30'
#     elif isotope == '1H_13C':
#         return pulprog == 'hsqcphpr'
#     # 1H experiment 21, 26, 31, 36
#     elif isotope == "1H_standard":
#         return pulprog == "zgpr"
#     # 1H experiment 25
#     elif isotope == "1H_mixture":
#         # 25, 30, 35, 40
#         if fid is not None and fid % 5 == 0:
#             return pulprog == "hsqcphpr"
#     return False
