[paths]
input_dir = /data/local/jy1008/MA-host-microbiome/NatChemBio_Data/LiveCellNMR-Cdiff/Data7_13CGlc1_Test/raw
output_dir = /data/local/jy1008/MA-host-microbiome/NatChemBio_Data/LiveCellNMR-Cdiff/Data7_13CGlc1_Test/processed_xlsx

# For use with s = Stack()
[experiment]
# 1H or 13C
spectra_type = 1H
# fid used to perform the calibration
first_fid = 52
